# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
  name: resourcehub
  demands:
  - Agent.Name -equals tnevrlka-agent

container: quay.io/redhat-appstudio/rhtap-task-runner:latest

steps:
- script: ls
